# Generated by Django 4.2.29 on 2026-05-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordcheck',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
